<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditEvents.aspx.cs" Inherits="EventsSystem.Admin.EditEvents" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<%--    <asp:UpdatePanel runat="server">
        <ContentTemplate>--%>
            <asp:RadioButtonList ID="RadioButtonListEvents" runat="server" AutoPostBack="true"
                OnSelectedIndexChanged="RadioButtonListEvents_SelectedIndexChanged" RepeatDirection="Horizontal">
                <asp:ListItem Text="Future Events" Selected="True" runat="server" />
                <asp:ListItem Text="Past Events" runat="server" />
            </asp:RadioButtonList>

<%--            <asp:UpdatePanel runat="server">
                <ContentTemplate>--%>
                    <h2>All events</h2>
                    <asp:GridView ID="GridViewEditEventsCurrent" runat="server" AllowSorting="True"
                        AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                        AutoGenerateEditButton="True" AutoGenerateSelectButton="True"
                        DataKeyNames="Id"
                        SelectMethod="GridViewEditEvents_GetData"
                        DeleteMethod="GridViewEditEventsCurrent_DeleteItem"
                        UpdateMethod="GridViewEditEventsCurrent_UpdateItem"
                        PageSize="5" AllowPaging="True"
                        OnSelectedIndexChanged="GridViewEditEventsCurrent_SelectedIndexChanged">
                        <Columns>
                            <asp:BoundField HeaderText="Id" DataField="Id" Visible="False" />
                            <asp:BoundField HeaderText="Title" DataField="Title" SortExpression="Title" />
                            <asp:BoundField HeaderText="Description" DataField="Description" />
                            <asp:BoundField HeaderText="Location" DataField="Location" SortExpression="Location" />
                            <asp:BoundField HeaderText="Date of Event" DataField="EventDate" SortExpression="EventDate" />
                        </Columns>
                    </asp:GridView>
<%--                </ContentTemplate>
            </asp:UpdatePanel>
        </ContentTemplate>
    </asp:UpdatePanel>--%>

<%--    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>--%>
            <asp:GridView ID="GridViewEditEventsPast" runat="server" AllowSorting="True"
                AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True" AutoGenerateSelectButton="True"
                DataKeyNames="Id"
                SelectMethod="GridViewEditEventsPast_GetData"
                UpdateMethod="GridViewEditEventsPast_UpdateItem"
                DeleteMethod="GridViewEditEventsPast_DeleteItem"
                PageSize="5" AllowPaging="True" Visible="False"
                OnSelectedIndexChanged="GridViewEditEventsCurrent_SelectedIndexChanged">
                <Columns>
                    <asp:BoundField HeaderText="Id" DataField="Id" Visible="False" />
                    <asp:BoundField HeaderText="Title" DataField="Title" SortExpression="Title" />
                    <asp:BoundField HeaderText="Description" DataField="Description" />
                    <asp:BoundField HeaderText="Location" DataField="Location" SortExpression="Location" />
                    <asp:BoundField HeaderText="Date of Event" DataField="EventDate" SortExpression="EventDate" />
                </Columns>
            </asp:GridView>
<%--        </ContentTemplate>
    </asp:UpdatePanel>--%>

<%--    <asp:UpdatePanel runat="server">
        <ContentTemplate>--%>
            <asp:Panel runat="server" ID="PanelEventsDetails">
                <h2 runat="server">Event details</h2>
                <asp:ListView ID="ListViewDetailsEvent" runat="server" ItemType="EventsSystem.Models.Event"
                    DataKeyNames="Id" SelectMethod="ListViewDetailsEvent_GetData">
                    <ItemTemplate>
                        <h3 runat="server"><%#: Item.Title %></h3>
                        <p runat="server">Date: <%#: Item.EventDate %></p>
                        <p runat="server">Description: <%#: Item.Description %></p>
                        <p runat="server">Location: <%#: Item.Location %></p>
                        <ul class="joinedUsers">
                            <asp:Repeater ID="RepeaterDetails" runat="server" ItemType="EventsSystem.Models.ApplicationUser" DataSource="<%# Item.Participants %>">
                                <HeaderTemplate>
                                    <asp:Literal ID="Literal1" runat="server"><h4>Users who joined the event</h4></asp:Literal>
                                </HeaderTemplate>
                                <ItemTemplate>
                                    <li>
                                        <img src='data:image/jpg;base64,<%# Item.ProfilePicture != null ? Convert.ToBase64String((byte[])Item.ProfilePicture) : string.Empty %>' alt="profile image" height="20" width="20" />
                                        <asp:Label ID="IdLabel" runat="server" Text='<%#: Item.UserName %>' />
                                    </li>
                                </ItemTemplate>
                            </asp:Repeater>
                        </ul>
                        <asp:LinkButton CssClass="btn btn-success" ID="ButtonClose" Text="Close" runat="server"
                            OnCommand="ButtonClose_Command" />
                    </ItemTemplate>
                </asp:ListView>
            </asp:Panel>
<%--        </ContentTemplate>
    </asp:UpdatePanel>--%>
</asp:Content>
