//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore_Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

     [DataContract(IsReference = true)]
    public partial class Artist
    {
        public Artist()
        {
            this.Songs = new HashSet<Song>();
            this.Albums = new HashSet<Album>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Country { get; set; }
        [DataMember]
        public System.DateTime DateOfBirth { get; set; }

        [DataMember]
        public virtual ICollection<Song> Songs { get; set; }
        [DataMember]
        public virtual ICollection<Album> Albums { get; set; }
    }
}
