//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore_Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

     [DataContract(IsReference = true)]
    public partial class Song
    {
        public int Id { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public int Year { get; set; }
        [DataMember]
        public string Genre { get; set; }
        [DataMember]
        public int ArtistId { get; set; }
        [DataMember]
        public int AlbumId { get; set; }

        [DataMember]
        public virtual Album Album { get; set; }
        [DataMember]
        public virtual Artist Artist { get; set; }
    }
}
